// COMMANDS는 이 플러그인이 노출하는 tauri::command 이름 목록 - permissions/autogenerated에
// 각 명령의 ACL 스텁을 생성하는 데 쓰인다. android_path("android")는 gen/android가 이
// 크레이트를 별도 Gradle 서브프로젝트로 자동 포함하도록(DEP_*_ANDROID_LIBRARY_PATH 경유)
// 표시한다 - 실제 gen/android/tauri.settings.gradle 갱신은 메인 앱의 build.rs
// (tauri_build::build())가 이 크레이트에 의존할 때 수행한다.
const COMMANDS: &[&str] = &["ping", "gtp_line"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
